### ISSUE TITLE
Split function used by scikit-learn random forest

### ISSUE THREAD

**Issue by iqbalu** [yassersouri/fast-bird-part-localization#2]
Hi,

Nice code! I was wondering which type of split function is used by scikit-learn library, any idea? I am not sure if typically used value/pixel difference split function will work well with hyper-column features, since there is no correlation between feature values.

Thanks!

**Comment by yassersouri** [comment]
Hi,

I'm not sure what do you mean by "split function". But I use the [RandomForestClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier) of scikit-learn as is.

For reference here is [the code](https://github.com/yassersouri/fast-bird-part-localization/blob/master/create_rf_model.py#L53).

But what you say is interesting to me. Can you clarify a bit more.

**Comment by iqbalu** [comment]
Hi,

So, at each node of the binary tree we want to split the data in two subsets. For this we first randomly select a set of feature/pixel locations and thresholds, and at each node select one combination that minimize/maximize a certain objective function (e.g., maximize information gain). Combination of feature locations and thresholds defines the set of split function i.e., at a selected feature location, if the feature value is greater than the selected threshold the sample in hand will go to left node, otherwise to the right node. Other options are you select two feature locations and define the split function based on the difference between their values, and so on there are many other options. I was just wondering which split function (feature value, difference of feature values, etc.) is used by default in scikit-learn since it can have a lot of impact on the final performance, e.g, difference of feature values will add more contextual information while splitting the data. In current case contextual information can be thought as how two different activation layers behaved at a certain pixel location. 

Hope it clarifies the question a bit more.

**Comment by yassersouri** [comment]
Thanks for the note.

Please notice that we classify pixels independently. So when the Random Forest classifier classifies a pixel it does not know which pixel it is.

The split function used in the scikit-learn is the original one in the 2001 paper by Breiman.
